[package]
name = "html_lite_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
html_lite_sections = { version = "0.1.0", path = "../html_lite_sections" }
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = "2.0.93"
